# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetracker',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
